const PERMISSIONS = {
  EDIT_COMPANY: 'edit_company',
  DELETE_COMPANY: 'delete_company',
  
  EDIT_BOOKING_SETTINGS: 'edit_booking_settings',
  
  VIEW_FINANCE: 'view_finance',
  
  VIEW_MEMBERS: 'view_members',
  MANAGE_MEMBERS: 'manage_members',
  
  VIEW_SERVICES: 'view_services',
  MANAGE_SERVICES: 'manage_services',
  
  VIEW_CUSTOMERS: 'view_customers',
  MANAGE_CUSTOMERS: 'manage_customers',
  
  VIEW_BOOKINGS: 'view_bookings',
  MANAGE_BOOKINGS: 'manage_bookings', 
  
  EDIT_SCHEDULE: 'edit_schedule',
};

export const ROLE_PERMISSIONS = {
  owner: Object.values(PERMISSIONS),
  
  admin: [
    PERMISSIONS.EDIT_COMPANY,
    PERMISSIONS.EDIT_BOOKING_SETTINGS,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.VIEW_SERVICES,
    PERMISSIONS.MANAGE_SERVICES,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
    PERMISSIONS.EDIT_SCHEDULE,
  ],
  
  manager: [
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.VIEW_SERVICES,
    PERMISSIONS.MANAGE_SERVICES,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
    PERMISSIONS.EDIT_SCHEDULE,
  ],

  receptionist: [
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_SERVICES,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
  ],
  
  member: [
    PERMISSIONS.VIEW_SERVICES,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.VIEW_MEMBERS,
  ],
};